### ISSUE TITLE
assets-manifest is not generated

### ISSUE THREAD

**Issue by winston0410** [TylorS/snowpack-plugin-hash#1]
I am trying to generate a manifest with this plugin, but it seems like it is not working correctly and the json file is not emitted.

This is my current setup:

```
plugins: [
    ['snowpack-plugin-content-hash', {
      hashLength: 4,
      assetManifest: 'asset-manifest.json'
    }]
]
```

**Comment by TylorS** [comment]
Hey @winston0410 thanks for trying the plugin out. If you're using precisely the above it would appear that the plugin name references `snowpack-plugin-content-hash` instead of `snowpack-plugin-hash`

**Comment by winston0410** [comment]
Oh right I have mistakenly used another plugin with similar name. After changing the plugin name, I can confirm that the manifest is generated. Great work Tylor!

**Comment by TylorS** [comment]
Thanks @winston0410. Please report back any odd issue along the way, I'm sure this isn't _quite_ 100%, I've never built stuff like this previously. Mainly I'm really unsure of the source map stuff..so please let me know if you run into anything
