### ISSUE TITLE
Registering service worker js file

### ISSUE THREAD

**Issue by dennis3001** [TylorS/snowpack-plugin-hash#13]
Hello,

Registering a service working requires referencing a URL of your js file

`navigator.serviceWorker.register("/sw.js").`

However the line above is not being processed by the plugin (neither in html, nor in js) so loading this file will fail.

**Comment by TylorS** [comment]
Hey @dennis3001 thanks for raising this issue, I really hadn't considered anything else besides import/export statements up until now.. this would be a great addition.

I'll see what I can do

**Comment by TylorS** [comment]
Hey @dennis3001  https://github.com/TylorS/typed-content-hash/pull/12 and v.0.15.0 of this plugin and have added support for this feature within a JS/TS file. I haven't yet added support for parsing JS inside of HTML as I haven't had the use-case previously

**Comment by TylorS** [comment]
Feel free to reopen if you have any further issues!
